<?php
// Include TCPDF library
require_once('../../tcpdf/tcpdf.php');

// Establish a database connection
require_once('../DbConfig.php');

// Retrieve the tourId from the form submission
$tourId = $_POST['tourId'];

// Retrieve the tour details from the database
$sql = "SELECT * FROM user_tours, new_plan WHERE tour_id = '$tourId' LIMIT 1";
$result = $conn->query($sql);
$row = $result->fetch_assoc();

// Generate the PDF content
$pdf = new TCPDF();
$pdf->SetMargins(20, 20, 20);
$pdf->AddPage();

// Add the TravelPal logo
// $pdf->Image('../../images/logo.png', 10, 10, 60, 0, 'PNG');

// Set the font
$pdf->SetFont('times', 'B', 14);

// Write the tour details
$pdf->Ln(10);
$pdf->Cell(0, 10, 'TravelPal Services Report', 0, 1, 'C');
$pdf->Ln(10);

// Set the font style and size for the additional details
$pdf->SetFont('helvetica', 'I', 10);

// Add "Report generated by" detail
$pdf->Cell(0, 10, 'Report generated by: TravelPal', 0, 1, 'R');

// Add "Generated date" detail
$generatedDate = date('Y-m-d'); // Get the current date
$pdf->Cell(0, 10, 'Generated date: ' . $generatedDate, 0, 1, 'R');

// Add "Generated time" detail
$generatedTime = date('H:i:s'); // Get the current time
$pdf->Cell(0, 10, 'Generated time: ' . $generatedTime, 0, 1, 'R');

// Set the font
$pdf->SetFont('times', 'B', 12);

$pdf->Ln(10);
$pdf->Cell(0, 10, 'Tour plan id: ' . $tourId, 0, 1, 'L');
$pdf->Cell(0, 10, 'Location: ' . $row['location'], 0, 1, 'L');
$pdf->Cell(0, 10, 'Tour plan type: ' . $row['type_of_package'], 0, 1, 'L');
$pdf->Cell(0, 10, 'Start date: ' . $row['start_date'], 0, 1, 'L');
$pdf->Cell(0, 10, 'No of Days: ' . $row['no_of_day'], 0, 1, 'L');
$pdf->Cell(0, 10, 'No of Tourists: ' . $row['no_of_tourist'], 0, 1, 'L');
$pdf->Cell(0, 10, 'Accommodation Services id: ' . $row['accomadation_id'], 0, 1, 'L');
$pdf->Cell(0, 10, 'Vehicle Services id: ' . $row['vehicle_id'], 0, 1, 'L');
$pdf->Cell(0, 10, 'Travel Guide Services id: ' . $row['guide_id'], 0, 1, 'L');
$pdf->Cell(0, 10, 'Total cost: Rs. ' . $row['final_price'], 0, 1, 'L');

// Output the PDF as a string
$pdfContent = $pdf->Output('', 'S');

// Set the appropriate content-type header to display the PDF
header('Content-Type: application/pdf');
header('Content-Disposition: inline; filename="exported.pdf"');

// Output the PDF content
echo $pdfContent;